use core::serde::Serde;
use eth_712_account::interface::{IAccount712AdminDispatcher, IAccount712AdminDispatcherTrait};
use openzeppelin::account::extensions::src9::OutsideExecution;
use openzeppelin::account::extensions::src9::interface::ISRC9_V2Dispatcher;
use openzeppelin::account::interface::ISRC6Dispatcher;
use openzeppelin::token::erc20::interface::IERC20Dispatcher;
use snforge_std::cheatcodes::CheatSpan;
use snforge_std::{
    ContractClassTrait, DeclareResultTrait, EventSpyTrait, cheat_block_timestamp, cheat_chain_id,
    cheat_nonce, cheat_resource_bounds, cheat_tip, cheat_transaction_version,
};
use starknet::account::Call;
use starknet::secp256_trait::Signature;
use starknet::{ClassHash, ContractAddress, EthAddress, ResourcesBounds, SyscallResultTrait};
use testing_utils::event_helpers::get_event_by_selector;

// ================================
// Fixed addresses for deterministic signatures
// ================================
// These addresses are used with deploy_at to ensure signatures remain valid
// regardless of contract code changes.

/// Fixed account contract address for EFO tests.
/// All pre-computed signatures use this address in the domain separator.
pub const FIXED_ACCOUNT_ADDRESS: felt252 = 0x07120acc07120acc07120acc07120acc;

/// Fixed ERC20 mock address for EFO tests with calls.
/// All pre-computed signatures involving ERC20 calls use this address.
pub const FIXED_ERC20_ADDRESS: felt252 = 0x0e2c200e2c200e2c200e2c200e2c2000;

/// Protocol address (zero) used as caller for __execute__.
pub const PROTOCOL_ADDRESS: felt252 = 0;

/// Class hash of the RegisterInterfacesEIC contract, used as upgrade target in signing tests.
/// Must match FIXED_UPGRADE_TARGET_CLASS_HASH in generate_test_signatures.py.
/// Re-run generate_test_signatures.py after recompiling if this contract changes.
pub const FIXED_UPGRADE_TARGET_CLASS_HASH: felt252 =
    0x4775e80641f54baffdce08e82de59d491bc9cbef8d674c7f76f94c2b80b1035;

/// Test Ethereum address corresponding to private key:
/// 0xa6d86467b6ec9e161649b27edfd8519e75a2e1cf5f4c309c628706e6999780e8
/// Address: 0xbF60187c5dFfA627249f1C3000A4168dbB9D7A1A
pub fn TEST_ETH_ADDRESS() -> EthAddress {
    0xbF60187c5dFfA627249f1C3000A4168dbB9D7A1A_felt252.try_into().unwrap()
}

/// Returns the ownership signature for TEST_ETH_ADDRESS.
/// This signature was generated by signing the OWNERSHIP_TRANSFER_MSG_HASH
/// (0xcb62b392614e2fd0ad1f7815a0e2748cf0ee2967170d7ab98d589d23d243075a)
/// with the test private key.
///
/// Values from: split_raw_eth_sig_to_felts output
/// '0xf05a84aad8f05fd0334fa09d30489e5a 0xc8480f3b625949e5a0c9c451743bde88
/// 0x1eaefed9d6e7dd3f98ec69b0ea381af4 0x513e4c818f64f7f953576a8ef106658f 0x1'
pub fn get_ownership_signature() -> Signature {
    Signature {
        r: u256 {
            low: 0xf05a84aad8f05fd0334fa09d30489e5a, high: 0xc8480f3b625949e5a0c9c451743bde88,
        },
        s: u256 {
            low: 0x1eaefed9d6e7dd3f98ec69b0ea381af4, high: 0x513e4c818f64f7f953576a8ef106658f,
        },
        y_parity: true // v = 28
    }
}

/// Returns an invalid signature for testing.
pub fn get_invalid_signature() -> Signature {
    Signature {
        r: u256 { low: 0x1234567890abcdef, high: 0xfedcba0987654321 },
        s: u256 { low: 0xabcdef1234567890, high: 0x1234567890abcdef },
        y_parity: false,
    }
}

/// Declare and deploy the StarknetEth712Account contract at FIXED_ACCOUNT_ADDRESS.
/// Returns the contract address and the class hash.
pub fn deploy_eth712_account() -> (ContractAddress, ClassHash) {
    let contract_class = snforge_std::declare("StarknetEth712Account")
        .unwrap_syscall()
        .contract_class();
    let fixed_address: ContractAddress = FIXED_ACCOUNT_ADDRESS.try_into().unwrap();
    let (contract_address, _) = contract_class.deploy_at(@array![], fixed_address).unwrap_syscall();
    (contract_address, *contract_class.class_hash)
}

/// Declare the RegisterInterfacesEIC contract and return its class hash.
pub fn declare_register_interfaces_eic() -> ClassHash {
    *snforge_std::declare("RegisterInterfacesEIC").unwrap_syscall().contract_class().class_hash
}

/// Deploy, initialize, and return an ISRC6Dispatcher for the account.
pub fn setup_initialized_account() -> ISRC6Dispatcher {
    let (account_address, _) = deploy_eth712_account();
    let account_contract = IAccount712AdminDispatcher { contract_address: account_address };
    account_contract.initialize(TEST_ETH_ADDRESS(), get_ownership_signature());
    ISRC6Dispatcher { contract_address: account_address }
}

/// Assert that an "Upgraded" event was emitted from the expected address with the expected class
/// hash.
pub fn assert_upgraded_event(
    ref spy: snforge_std::EventSpy, account_address: ContractAddress, expected_class_hash: felt252,
) {
    let events = spy.get_events();
    let event_option = get_event_by_selector(events.events.span(), selector!("Upgraded"));
    assert!(event_option.is_some(), "Upgraded event not found");
    let (from, event) = event_option.unwrap();
    assert!(*from == account_address, "Event from wrong address");
    assert!(*event.data.at(0) == expected_class_hash, "Wrong class hash in event");
}

// ================================
// Execute-from-outside (EFO) test setup helpers
// ================================

/// Setup an initialized account with configurable timestamp for EFO tests.
/// Returns src9_dispatcher (use src9.contract_address if account address is needed).
pub fn setup_efo_test_with_timestamp(timestamp: u64) -> ISRC9_V2Dispatcher {
    let (account_address, _) = deploy_eth712_account();
    let account_contract = IAccount712AdminDispatcher { contract_address: account_address };
    account_contract.initialize(TEST_ETH_ADDRESS(), get_ownership_signature());
    cheat_block_timestamp(account_address, timestamp, CheatSpan::Indefinite);
    cheat_chain_id(account_address, 'SN_MAIN', CheatSpan::Indefinite);
    ISRC9_V2Dispatcher { contract_address: account_address }
}

/// Setup an initialized account with default TEST_TIMESTAMP for EFO tests.
/// Returns src9_dispatcher (use src9.contract_address if account address is needed).
pub fn setup_efo_test() -> ISRC9_V2Dispatcher {
    setup_efo_test_with_timestamp(TEST_TIMESTAMP)
}

/// Setup an initialized account with ERC20 mock for EFO tests.
/// Returns (src9_dispatcher, token_address, erc20_dispatcher).
pub fn setup_efo_test_with_erc20() -> (ISRC9_V2Dispatcher, ContractAddress, IERC20Dispatcher) {
    let src9 = setup_efo_test();
    let (token_address, token) = deploy_mock_erc20(src9.contract_address);
    (src9, token_address, token)
}

// ================================
// __validate__ / __execute__ test setup
// ================================

/// Fixed resource bounds for __validate__ tests.
/// Must match VALIDATE_RESOURCE_BOUNDS in generate_test_signatures.py.
pub fn validate_resource_bounds() -> Span<ResourcesBounds> {
    array![
        ResourcesBounds { resource: 'L1_GAS', max_amount: 100, max_price_per_unit: 1000 },
        ResourcesBounds { resource: 'L2_GAS', max_amount: 200, max_price_per_unit: 2000 },
        ResourcesBounds { resource: 'L1_DATA', max_amount: 300, max_price_per_unit: 3000 },
    ]
        .span()
}

/// Setup an initialized account with all tx_info fields cheated for __validate__/__execute__ tests.
/// Cheats: chain_id, version, nonce, resource_bounds, tip.
/// Signature must be cheated separately per test.
/// Returns (src6_dispatcher, account_address).
pub fn setup_validate_test() -> (ISRC6Dispatcher, ContractAddress) {
    let (account_address, _) = deploy_eth712_account();
    let account_contract = IAccount712AdminDispatcher { contract_address: account_address };
    account_contract.initialize(TEST_ETH_ADDRESS(), get_ownership_signature());

    cheat_chain_id(account_address, 'SN_MAIN', CheatSpan::Indefinite);
    cheat_transaction_version(account_address, 3, CheatSpan::Indefinite);
    cheat_nonce(account_address, VALIDATE_NONCE_EMPTY, CheatSpan::Indefinite);
    cheat_resource_bounds(account_address, validate_resource_bounds(), CheatSpan::Indefinite);
    cheat_tip(account_address, 0, CheatSpan::Indefinite);

    (ISRC6Dispatcher { contract_address: account_address }, account_address)
}

// ================================
// OutsideExecution test fixtures
// ================================

/// Fixed timestamps for testing execute_from_outside_v2.
pub const EXECUTE_AFTER: u64 = 1000;
pub const EXECUTE_BEFORE: u64 = 3000;
pub const TEST_TIMESTAMP: u64 = 2000;
pub const TEST_NONCE: felt252 = 1;

/// ANY_CALLER constant from SNIP-9.
pub const ANY_CALLER: felt252 = 'ANY_CALLER';

/// Returns a test OutsideExecution with fixed values and empty calls.
/// Using empty calls to avoid ENTRYPOINT_NOT_FOUND errors during testing.
pub fn get_test_outside_execution() -> OutsideExecution {
    OutsideExecution {
        caller: ANY_CALLER.try_into().unwrap(),
        nonce: TEST_NONCE,
        execute_after: EXECUTE_AFTER,
        execute_before: EXECUTE_BEFORE,
        calls: array![].span() // Empty calls for testing
    }
}

/// Returns an invalid signature for testing signature validation.
pub fn get_invalid_outside_execution_signature() -> Array<felt252> {
    array![
        0x1234567890abcdef1234567890abcdef, // r_high (invalid)
        0xfedcba0987654321fedcba0987654321, // r_low
        0xabcdef1234567890abcdef1234567890, // s_high
        0x0987654321fedcba0987654321fedcba, // s_low
        27, // v
        1 // chain_id
    ]
}

// ================================
// ERC20 Mock helpers for execute_from_outside tests
// ================================

/// Initial supply for mock ERC20 token.
pub const MOCK_ERC20_INITIAL_SUPPLY: u256 = 1000_u256;

/// Deploy a mock ERC20 token at FIXED_ERC20_ADDRESS with initial supply minted to the owner.
/// Returns (token_address, dispatcher).
pub fn deploy_mock_erc20(owner: ContractAddress) -> (ContractAddress, IERC20Dispatcher) {
    let contract_class = snforge_std::declare("DualCaseERC20Mock")
        .unwrap_syscall()
        .contract_class();

    // Constructor: (name, symbol, decimals, initial_supply, recipient)
    let mut calldata: Array<felt252> = array![];
    let name: ByteArray = "MockToken";
    name.serialize(ref calldata);
    let symbol: ByteArray = "MTK";
    symbol.serialize(ref calldata);
    let decimals: u8 = 18;
    decimals.serialize(ref calldata);
    MOCK_ERC20_INITIAL_SUPPLY.serialize(ref calldata);
    owner.serialize(ref calldata);

    let fixed_address: ContractAddress = FIXED_ERC20_ADDRESS.try_into().unwrap();
    let (token_address, _) = contract_class.deploy_at(@calldata, fixed_address).unwrap_syscall();
    let dispatcher = IERC20Dispatcher { contract_address: token_address };
    (token_address, dispatcher)
}

/// Fixed spender address used in pre-computed approve call signatures.
pub const APPROVE_SPENDER: felt252 = 0x1234;

/// Fixed approve amount used in pre-computed approve call signatures.
pub const APPROVE_AMOUNT: u256 = 500_u256;

/// Returns the fixture approve Call matching pre-computed signatures.
pub fn get_approve_call() -> Call {
    let token_address: ContractAddress = FIXED_ERC20_ADDRESS.try_into().unwrap();
    let spender: ContractAddress = APPROVE_SPENDER.try_into().unwrap();
    Call {
        to: token_address,
        selector: selector!("approve"),
        calldata: array![spender.into(), APPROVE_AMOUNT.low.into(), APPROVE_AMOUNT.high.into()]
            .span(),
    }
}

/// Build a transfer Call for ERC20.
pub fn build_transfer_call(
    token_address: ContractAddress, recipient: ContractAddress, amount: u256,
) -> Call {
    Call {
        to: token_address,
        selector: selector!("transfer"),
        calldata: array![recipient.into(), amount.low.into(), amount.high.into()].span(),
    }
}

/// EFO nonces for different test scenarios (to avoid conflicts).
pub const NONCE_SINGLE_CALL: felt252 = 100;
pub const NONCE_MULTI_CALL: felt252 = 101;
pub const NONCE_ATOMICITY: felt252 = 102;
pub const NONCE_SPECIFIC_CALLER: felt252 = 103;
pub const NONCE_EFO_UPGRADE: felt252 = 200;

/// __validate__ nonces matching generate_test_signatures.py.
pub const VALIDATE_NONCE_EMPTY: felt252 = 0;
pub const VALIDATE_NONCE_WITH_CALLS: felt252 = 1;
pub const VALIDATE_NONCE_UPGRADE: felt252 = 2;

/// Specific caller address for testing non-ANY_CALLER scenarios.
pub const SPECIFIC_CALLER: felt252 = 0xCAFE;

/// Build OutsideExecution with specified calls (uses ANY_CALLER).
pub fn build_outside_execution_with_calls(calls: Span<Call>, nonce: felt252) -> OutsideExecution {
    OutsideExecution {
        caller: ANY_CALLER.try_into().unwrap(),
        nonce,
        execute_after: EXECUTE_AFTER,
        execute_before: EXECUTE_BEFORE,
        calls,
    }
}

/// Build OutsideExecution with a specific caller (not ANY_CALLER).
pub fn build_outside_execution_with_specific_caller(
    nonce: felt252, caller: ContractAddress,
) -> OutsideExecution {
    OutsideExecution {
        caller,
        nonce,
        execute_after: EXECUTE_AFTER,
        execute_before: EXECUTE_BEFORE,
        calls: array![].span(),
    }
}

// GENERATED-SIGNATURES-START (by scripts/generate_test_signatures.py -- do not edit manually)

/// EFO signature: empty ArcxExecution calls, nonce=1, chain_id=1.
pub fn get_outside_execution_signature() -> Array<felt252> {
    array![
        0x2135fdc65da83ba35afb8b7839aa9a1e, 0xc5f151ba34a91e1ad2c15d3fa0a84524,
        0x67fcbae6638b6902bcb5493067dc5bc2, 0x557960ca64baa7953004fb37a0f356a2, 28, 1,
    ]
}

/// EFO signature: empty ArcxExecution calls, nonce=1, chain_id=2.
pub fn get_signature_evm_chain_id_2() -> Array<felt252> {
    array![
        0x71796ed4bda4f7b83b402c71e17783d4, 0xd22372be5159e3529ccaa2d956d29a0f,
        0x28305c2d6ada573bfc5de34113726343, 0xef18f5e303cfd90d52500dbb839c82ca, 28, 2,
    ]
}

/// EFO signature signed with SN_SEPOLIA domain (fails against SN_MAIN).
pub fn get_signature_wrong_sn_chain_name() -> Array<felt252> {
    array![
        0x3b12cc379210e08f6f48be36bd75d5ee, 0x8f5ee64b45619a7c4bc7699843adcdaa,
        0x5a3ae1381a9f096922c09abda61cc455, 0x9060e4c06ff9e98749709de4bdad2524, 27, 1,
    ]
}

/// EFO signature signed with wrong contract address (domain mismatch).
pub fn get_signature_wrong_contract_address() -> Array<felt252> {
    array![
        0x3c862242455ea3718871aeaeee950f72, 0xc44cb7f534dd7a74401471f265f822f1,
        0x19c9687dd9dc762ac65fdcc916426ee8, 0x36dfb8bcda9b31d1ca161f8187a11f90, 28, 1,
    ]
}

/// EFO signature: approve(0x1234, 500), nonce=100.
pub fn get_single_call_approve_signature() -> Array<felt252> {
    array![
        0x14bf4fd134ac5e3680addff2580496d6, 0x17667a72ed64e9210ab113058bb7b8e3,
        0x64cac333aa25e37085ddc578ed08c61b, 0xae844f10253f80c991f89ebfd61c6c6b, 28, 1,
    ]
}

/// EFO signature: approve(500) + transfer(100), nonce=101.
pub fn get_multi_call_signature() -> Array<felt252> {
    array![
        0xfec375e6720cb6a14be0fccff43d1ae0, 0x3e1b96f960d31dd8d0ed2e1af463e0b6,
        0x4deb79c4ac42bde0fe7356a8a872384e, 0x3b957e5e94e8ff0a5700ee38b64c6a4b, 28, 1,
    ]
}

/// EFO signature: approve(500) + transfer(1001, fails), nonce=102.
pub fn get_atomicity_test_signature() -> Array<felt252> {
    array![
        0xa0331e31fcc4e19d4dba7f5e07be0635, 0xe8f0d86480f3ad684044b4728046969c,
        0x722e6c524c301956e0ed7110ee522257, 0xebe4901cda899634c1884ef2a68f0da7, 27, 1,
    ]
}

/// EFO signature: specific caller=0xCAFE, nonce=103, empty calls.
pub fn get_specific_caller_signature() -> Array<felt252> {
    array![
        0x48bd92070292fe1ba4a18f5b84cdadb8, 0xbc52fd0efd69c6ed686db1f384fe00c5,
        0x6f0e7dbb824bfe1125b8d760ead04297, 0xf986b450b5c746ac065dbb12f63221e5, 27, 1,
    ]
}

/// __validate__ signature: empty calls, nonce=0.
pub fn get_validate_empty_calls_signature() -> Array<felt252> {
    array![
        0x0c7ab95484df32ee1f457501214b5c51, 0x0fd461a1c92f777d97545e640f893731,
        0x78afd3e69cdf4b6c57b49b8fd719ff0e, 0x24553f8f1b1cdb5121ef8641a2dbcab5, 28, 1,
    ]
}

/// __validate__ signature: approve(0x1234, 500), nonce=1.
pub fn get_validate_with_approve_signature() -> Array<felt252> {
    array![
        0xfdf4a332c8f6bded4b9670e59d8d90e6, 0xb1c10fd29b606f3522c62fc237d5ec1f,
        0x7a4518381cf3240b4b96169848677726, 0xf642df7a6d69205f1f390f6205adab44, 27, 1,
    ]
}

/// __validate__ signature signed with SN_SEPOLIA domain (fails against SN_MAIN).
pub fn get_validate_wrong_chain_signature() -> Array<felt252> {
    array![
        0x455a3be29526aebe2731210b357f666b, 0x1ca8edb5a5e21e7f16f9b2d663fe0141,
        0x629a920e9971312499308cbadf8d0d25, 0xb406cd3e690bead8d1923dfd93a5a466, 28, 1,
    ]
}

/// EFO signature: upgrade(FIXED_UPGRADE_TARGET_CLASS_HASH, None), nonce=200.
pub fn get_efo_upgrade_signature() -> Array<felt252> {
    array![
        0x131eb773a1f346e3668e462a2c97f45f, 0x4b82fee55f6c54fab61706cad4878a85,
        0x02a7e8409a556e82d3bdb9fb3cdaec58, 0x397b6ecb89edd6ba4acbbed18de17ba4, 28, 1,
    ]
}

/// __validate__ signature: upgrade(FIXED_UPGRADE_TARGET_CLASS_HASH, None), nonce=2.
pub fn get_validate_upgrade_signature() -> Array<felt252> {
    array![
        0xb4146b116881b636b3e5df03f3d88139, 0x522594e6adbc196ed5747efc87f8e896,
        0x77d92acd1c9e71fc89917065b8bb20d7, 0xfcdbe021378a82e41a644300aa089f2d, 28, 1,
    ]
}
// GENERATED-SIGNATURES-END
